# -*- coding: utf-8 -*-
"""НПОР.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SA5CadgzX0PfzMDFGUv8GWs0Q8mjnyGM
"""

import numpy as np
import matplotlib.pyplot as plt

"""Ядро Епанечникова"""

def kernel(z):
    if abs(z) <= 1:
        return 0.75 * (1 - z**2)
    return 0.0

kernel_vec = np.vectorize(kernel)

"""НПР"""

def npr_predict(x_train, y_train, x0, beta):
    h = beta * n**(-1/5)
    z = (x0 - x_train) / h
    weights = kernel_vec(z)
    if np.sum(weights) == 0:
        return 0
    return np.sum(weights * y_train) / np.sum(weights)

def loo_mse(x, y, beta):
    n = len(x)
    errors = []

    for i in range(n):
        x_train = np.delete(x, i)
        y_train = np.delete(y, i)
        y_pred = npr_predict(x_train, y_train, x[i], beta)
        errors.append((y[i] - y_pred) ** 2)

    return np.mean(errors)
if __name__ == "__main__":
    """Установка размера и качества Данных"""

    n = 80
    x = np.random.uniform(-3, 7, n)
    noise = np.random.normal(0, 0.3, n)
    y = 0.1*(x-4)*np.cos(x) + 0.5*x + noise

    """Поиск лучшего beta"""

    betas = np.arange(0.1, 2.01, 0.1)
    mse_values = []

    for beta in betas:
        mse = loo_mse(x, y, beta)
        mse_values.append(mse)

    best_beta = betas[np.argmin(mse_values)]
    print("Оптимальное β:", best_beta)
    print("Минимальный MSE:", min(mse_values))
    